version: "3.9"
services:
  server1:
    restart: on-failure
    environment:
      - SERVER_NUMBER=1
      - PORT=5000
    build: .

  server2:
    restart: on-failure
    environment:
      - SERVER_NUMBER=2
      - PORT=5001
    build: .

  server3:
    restart: on-failure
    environment:
      - SERVER_NUMBER=3
      - PORT=5002
    build: .

  nginx:
    restart: on-failure
    build: ./nginx
    ports:
      - "80:80"   
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - Server1
      - Server2
